import React, { forwardRef, useRef, useState } from "react";
import { BenefitsWrapper } from "./styled";

import free from "../../assets/benefits/free.png";
import purchase from "../../assets/benefits/purchase.png";
import reward from "../../assets/benefits/reward.png";
import app from "../../assets/benefits/app.png";
import group from "../../assets/benefits/group.png";

function Benefits() {
  return (
    <BenefitsWrapper className="benefits">
      <div className="content">
        <h1 className="content_title">NFT Pools Phone Benefits</h1>

        <div className="content_list">
          <div className="list_item">
            <div className="img_item">
              <img src={free} alt="img" width="100%" height="100%" />
            </div>
            
            <div className="list_text">
              <h3 className="content_t">
                Free supply of 1 phone for the first time
              </h3>
              <p className="content_p">
                Holders of POOLS Phone NFT will receive one POOLS Phone free of
                charge when it is released from May to July 2023.
              </p>
            </div>
          </div>

          <div className="list_item">
            <div className="img_item">
              <img src={purchase} alt="img" width="100%" height="100%" />
            </div>
            
            <div className="list_text">
              <h3 className="content_t">NFT Purchase Discount </h3>
              <p className="content_p">
                When purchasing through NFT Roulette, participants receive five
                TIERs of differential discounts. (10~50%)
              </p>
            </div>
          </div>

          <div className="list_item">
            <div className="img_item">
              <img src={reward} alt="img" width="100%" height="100%" />
            </div>
            
            <div className="list_text">
              <h3 className="content_t">POOLS Phone Sales Reward </h3>
              <p className="content_p">
                During the POOLS Phone sale, holders of 10,000 NFTs receive a
                sales dividend. When a POOLS Phone NFT card is transferred the
                cardholder's dividend is lost, and this dividend is distributed
                to the person who received the transfer.{" "}
              </p>
            </div>
          </div>

          <div className="list_item">
            <div className="img_item">
              <img src={app} alt="img" width="100%" height="100%" />
            </div>
            
            <div className="list_text">
              <h3 className="content_t">
                POOLS Phone App Store Revenue Reward
              </h3>
              <p className="content_p">
                POOLS Phone automatically compensates a portion of the revenue
                generated by the POOLS App store. The compensation ratio is
                applied differently depending on the NFT tier.
              </p>
            </div>
          </div>

          <div className="list_item">
            <div className="img_item">
              <img src={group} alt="img" width="100%" height="100%" />
            </div>
            
            <div className="list_text">
              <h3 className="content_t">Phone Purchase Referral Reward</h3>
              <p className="content_p">
                NFT holders are given a referral code from the POOLS Phone
                pre-sale site and will receive a portion of the sales incentives
                when someone uses their code to make a purchase. The incentives,
                however, differ depending on the tier.
              </p>
            </div>
          </div>
        </div>
      </div>
    </BenefitsWrapper>
  );
}
export default forwardRef(Benefits);
